DROP TABLE IF EXISTS section_retrieved CASCADE;
DROP TABLE IF EXISTS message CASCADE;
DROP TABLE IF EXISTS conversation CASCADE;
DROP TABLE IF EXISTS project CASCADE;

CREATE TABLE project (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE conversation (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              helpdesk_id BIGINT NOT NULL,
                              project_id BIGINT NOT NULL,
                              handover_to_human_needed BOOLEAN DEFAULT FALSE NOT NULL,
                              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

                              CONSTRAINT fk_conversation_project
                                  FOREIGN KEY (project_id)
                                      REFERENCES project(id)
);

CREATE TABLE message (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         conversation_id BIGINT NOT NULL,
                         role VARCHAR(10) NOT NULL CHECK (role IN ('USER', 'AGENT')),
                         content TEXT NOT NULL,
                         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

                         CONSTRAINT fk_message_conversation
                             FOREIGN KEY (conversation_id)
                                 REFERENCES conversation(id)
                                 ON DELETE CASCADE
);

CREATE TABLE section_retrieved (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   message_id BIGINT NOT NULL,
                                   score NUMERIC(6, 5) NOT NULL,
                                   content TEXT NOT NULL,

                                   CONSTRAINT fk_section_retrieved_message
                                       FOREIGN KEY (message_id)
                                           REFERENCES message(id)
                                           ON DELETE CASCADE
);
